### ISSUE TITLE
pinyin error

### ISSUE THREAD

**Issue by zileyuan** [breeswish/pinyinlite#1]
pinyinlite('世界你好'));

result : zhong,mo,ji,zheng,jiu,zhuo,ge,lin,ya,chuan,chan,guan,zhang,kuang,jie,feng,yu,san,pi,ding,si,zhuan,ju,cheng,qiu,qie,bing,dong,cong,ye,jiang,bu,mian,shu,sang,li,diu,you,liang,yan,gai,chou,kao,yi,dan,ba,jing,shang,xia,zhu,wei,shi,shi,qi,wan,pie,dian,xuan,kei,la,mo,lun,qu,wan,li,jian,nao,xian,huo,kuang,zhan,yan,you,ji,xian,jie,zhi,tang,men,xu,pa,duan,jiao,xiang,chang,zhuan,xia,yi,pin,you,jie,xiang,di,juan,yi,zheng,gui,fa,jia,shao,bi,fo,zhao,yang,si,si,zuo,ti,zhan,dan,ni,qu,wei,wa,chan,xian,ci,tian,ge,fu,zhu,e,ei,lao,gan,shi,quan,tiao,ming,hen,he,ning,yong,she,bing,gou,tuo,ka,huai,bao,chong,shen,si,hao,dui,qia,wan,chan,zhang,la,tou,lve,xian,ga,qing,guan,wu,duo,dian,jia,lie,qiao,dou,bu,bo,wen,xiang,sui,lu,ni,hou,zhong,tuo,tu,si,lue,fei,zhong,gou,yi,guan,die,zhan,xing,ji,nan,shan,lao,hao,yue,lan,zui

**Comment by SummerWish** [comment]
Hello, I cannot reproduce this issue. Can you post more information here?

**Comment by zileyuan** [comment]
`<!DOCTYPE html>
<html>
	<head>
		<script src="./pinyinlite.js"></script>
	</head>
	<body>
		<script type="text/javascript" charset="utf-8">
		alert(pinyinlite('世界你好'));
		</script>
	</body>
</html>`

**Comment by zileyuan** [comment]
![9999999999](https://cloud.githubusercontent.com/assets/5235605/15175889/0a99a1ca-179b-11e6-85ac-e27cb073cdd4.png)

**Comment by SummerWish** [comment]
该问题是浏览器未能正确识别 pinyinlite.js 的编码所致。

请在引用 pinyinlite.js 时候添加 charset 属性:

```html
<script charset="UTF-8" src="dist/pinyinlite.min.js"></script>
```
