### ISSUE TITLE
用例子中的增长测试，发现增被识别成多音字，我查了下，增不是多音字。

### ISSUE THREAD

**Issue by beiguancyc** [breeswish/pinyinlite#2]
![image](https://cloud.githubusercontent.com/assets/12932389/25780758/349e63d4-3360-11e7-935a-b0811630c2cb.png)

**Comment by breeswish** [comment]
字典现在改成 pinyin-data 生成了，它的数据来自于《漢語大字典》和《现代汉语词典》

Ref:
https://github.com/mozillazg/pinyin-data/blob/master/pinyin.txt#L8482
https://zh.wiktionary.org/zh-hans/%E5%A2%9E
