### ISSUE TITLE
调用pinyinlite("王") 的返回[0:"yu",1 : "wang"]

### ISSUE THREAD

**Issue by windyinwind** [breeswish/pinyinlite#4]
![wrongpingyin](https://user-images.githubusercontent.com/6670397/28653835-7b50db26-72c2-11e7-8a03-b6789db2bc4b.png)

**Comment by breeswish** [comment]
“王”有 yu 的读音：

https://zh.wiktionary.org/zh-hans/%E7%8E%8B

**Comment by windyinwind** [comment]
是我鄙陋了，不过如果常用应在第一会好一些
