### ISSUE TITLE
啊 返回的A带有一声 声调

### ISSUE THREAD

**Issue by Murrayee** [breeswish/pinyinlite#5]
![image](https://user-images.githubusercontent.com/20828177/29492489-75cae124-85af-11e7-9d7c-84c63af1fab2.png)

**Comment by breeswish** [comment]
I published version 1.2.1, hoping fixed this issue. Could you take a look?

**Comment by breezewish** [comment]
It should be fixed. Closing. If the problem still exists, please leave a reply here.
